name: Generate Daily Blog Post

on:
  workflow_dispatch:
  schedule:
    - cron: '0 9 * * *' # Run daily at 9am UTC

permissions:
  contents: write
  pull-requests: write

jobs:
  generate-blog-post:
    name: Generate Daily Blog Post
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'yarn'

      - name: Install Yarn
        run: npm install -g yarn

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Configure Branch Name
        run: |
          # Create a new branch with today's date
          DATE=$(date +"%Y-%m-%d")
          BRANCH_NAME="blog-post-${DATE}"
          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV
          echo "DATE=$DATE" >> $GITHUB_ENV

      - name: Generate blog post
        run: yarn generate-post
        env:
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}

      - name: Create PR
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: Add new post | ${{ env.DATE }}
          title: Add new post | ${{ env.DATE }}
          labels: allow-auto-merge
          branch: ${{ env.BRANCH_NAME }}
          token: ${{ secrets.AUTO_MERGE_TOKEN }}
