name: Generate Daily Blog Post

on:
  workflow_dispatch:
  schedule:
    - cron: '0 9 * * *' # Run daily at 9am UTC

jobs:
  generate-blog-post:
    name: Generate Daily Blog Post
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'yarn'

      - name: Install Yarn
        run: npm install -g yarn

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Create branch for new post
        run: |
          # Create a new branch with today's date
          DATE=$(date +"%Y-%m-%d")
          BRANCH_NAME="blog-post-${DATE}"
          git checkout -b $BRANCH_NAME
          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV

      - name: Generate blog post
        env:
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
        run: yarn generate-post

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          git add posts/
          git commit -m "Add new blog post for $(date +"%Y-%m-%d")"
          git push --set-upstream origin $BRANCH_NAME

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: 'Add new post'
          body: |
            This PR adds a new AI-generated blog post for today.
            Generated by the Daily Blog Post workflow.
          branch: ${{ env.BRANCH_NAME }}
          base: master
          labels: 'allow-auto-merge'
